### PR TITLE
Retry unacknowledged messages

### PR DESCRIPTION
**Pull request by pflueras**
Retry unanswered messages initially delivered to a node which has just left the cluster.
This PR covers the cases where unanswered messages are redelivered either locally or remotely to a new node.
This PR guarantees that ongoing messages processed by a crushed node are redelivered onto another node from the cluster.

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@pflueras I have merged. I have a question. What does `UnAck...` mean. Does it mean Nak or does it mean that a message that should have been acknowledged has not been? And, under what circumstances is the message sent and from where? Just trying to make sure I follow. Thanks.

**Comment by pflueras** [comment]
`Unack...` means indeed `Nak...`. It is an ongoing message running on a different node from cluster.
Outcome (i.e. 'returns' from `Answer` message) of this message is awaited on current node in order to continue `Completes` pipeline execution.
Hopefully I answered to your questions.

**Comment by VaughnVernon** [comment]
Ok, thanks. Do you think that `NakMessage` would be a better name?

**Comment by pflueras** [comment]
Yes, definitely! I will do the necessary changes.

**Comment by VaughnVernon** [comment]
@pflueras As discussed, let's leave this as is. I now understand correctly that this represents and message that is to be sent, which means it is now unacknowledged, and also when resent because after previously being sent was not acknowledged and thus is still unacknowledged.

**Comment by pflueras** [comment]
I agree! 👍

**Pull request merged**
